// ==========================================================================
//  DPI-C Bridge for SVA + Coverage Engine
//  These functions are called from SystemVerilog (generated by svpp.py)
// ==========================================================================
#include "sva_engine.h"
#include "svdpi.h"

#include <cstring>
#include <vector>

using namespace sva;

// DPI export from SV — calls `uvm_error in SystemVerilog context
extern "C" void sva_uvm_error(const char* id, const char* msg);

static svScope sva_tick_scope = nullptr;

extern "C" {

// ==================================================================
//  Initialization / Finalization
// ==================================================================
static void sva_fail_cb(const char* name, const char* msg) {
    if (sva_tick_scope) svSetScope(sva_tick_scope);
    sva_uvm_error(name, msg);
}

void sva_init(void) {
    // Engine is a singleton — auto-initialized on first access
    Engine::instance().set_fail_callback(sva_fail_cb);
}

void sva_register_uvm_scope(void) {
    // Called from tb_top initial block — save this scope for UVM error calls
    sva_tick_scope = svGetScope();
    Engine::instance().set_fail_callback(sva_fail_cb);
}

void sva_final(void) {
    Engine::instance().report("sva_report.txt");
}

void sva_reset(void) {
    Engine::instance().reset();
}

// ==================================================================
//  Signal Management
// ==================================================================
void sva_set(const char* signal_name, long long value) {
    Engine::instance().set_signal(signal_name, (int64_t)value);
}

// ==================================================================
//  Assertion Management
// ==================================================================
int sva_assert_create(const char* name, const char* prop_expr, int kind) {
    return Engine::instance().create_assertion(name, prop_expr, kind);
}

int sva_assert_create_ex(const char* name, const char* prop_expr, int kind,
                          const char* file, int line) {
    return Engine::instance().create_assertion(name, prop_expr, kind, file, line);
}

void sva_assert_set_message(int id, const char* msg) {
    auto* a = Engine::instance().get_assertion(id);
    if (a) a->fail_message = msg;
}

void sva_assert_enable(int id, int enable) {
    auto* a = Engine::instance().get_assertion(id);
    if (a) a->enabled = (enable != 0);
}

// Tick ALL assertions with current signal values
void sva_tick(long long sim_time) {
    static bool cb_set = false;
    if (!cb_set) {
        Engine::instance().set_fail_callback(sva_fail_cb);
        cb_set = true;
    }
    Engine::instance().tick((uint64_t)sim_time);
}

// Query assertion results
long long sva_assert_pass_count(int id) {
    auto* a = Engine::instance().get_assertion(id);
    return a ? (long long)a->pass_count : 0;
}

long long sva_assert_fail_count(int id) {
    auto* a = Engine::instance().get_assertion(id);
    return a ? (long long)a->fail_count : 0;
}

long long sva_assert_vacuous_count(int id) {
    auto* a = Engine::instance().get_assertion(id);
    return a ? (long long)a->vacuous_count : 0;
}

// ==================================================================
//  Covergroup Management
// ==================================================================
int sva_cg_create(const char* name) {
    return Engine::instance().create_covergroup(name);
}

int sva_cg_add_coverpoint(int cg_id, const char* cp_name) {
    return Engine::instance().cg_add_coverpoint(cg_id, cp_name);
}

void sva_cg_add_bin(int cp_id, const char* bin_name,
                     long long lo, long long hi) {
    Engine::instance().cg_add_bin(cp_id, bin_name, lo, hi);
}

void sva_cg_add_bin_list(int cp_id, const char* bin_name,
                          const long long* values, int count) {
    std::vector<int64_t> vals(values, values + count);
    Engine::instance().cg_add_bin_list(cp_id, bin_name, vals);
}

void sva_cg_add_transition_bin(int cp_id, const char* bin_name,
                                const long long* seq, int len) {
    std::vector<int64_t> s(seq, seq + len);
    Engine::instance().cg_add_transition_bin(cp_id, bin_name, s);
}

void sva_cg_add_wildcard_bin(int cp_id, const char* bin_name,
                              long long mask, long long pattern) {
    Engine::instance().cg_add_wildcard_bin(cp_id, bin_name,
                                           (uint64_t)mask, (uint64_t)pattern);
}

void sva_cg_add_illegal_bin(int cp_id, const char* bin_name,
                             long long lo, long long hi) {
    Engine::instance().cg_add_illegal_bin(cp_id, bin_name, lo, hi);
}

void sva_cg_add_ignore_bin(int cp_id, const char* bin_name,
                            long long lo, long long hi) {
    Engine::instance().cg_add_ignore_bin(cp_id, bin_name, lo, hi);
}

void sva_cg_add_default_bin(int cp_id, const char* bin_name) {
    Engine::instance().cg_add_default_bin(cp_id, bin_name);
}

void sva_cg_add_auto_bins(int cp_id, int count) {
    Engine::instance().cg_add_auto_bins(cp_id, count);
}

// Cross coverage (2-way shorthand)
int sva_cg_add_cross2(int cg_id, const char* name, int cp_a, int cp_b) {
    std::vector<int> ids = {cp_a, cp_b};
    return Engine::instance().cg_add_cross(cg_id, name, ids);
}

// Cross coverage (3-way)
int sva_cg_add_cross3(int cg_id, const char* name, int a, int b, int c) {
    std::vector<int> ids = {a, b, c};
    return Engine::instance().cg_add_cross(cg_id, name, ids);
}

// Cross coverage (N-way via array)
int sva_cg_add_cross_n(int cg_id, const char* name,
                        const int* cp_ids, int count) {
    std::vector<int> ids(cp_ids, cp_ids + count);
    return Engine::instance().cg_add_cross(cg_id, name, ids);
}

// Sample a single coverpoint with a value
void sva_cg_sample_point(int cp_id, long long value) {
    Engine::instance().cg_sample_point(cp_id, (int64_t)value);
}

// Finalize sampling for a covergroup (processes cross coverage)
void sva_cg_sample(int cg_id) {
    Engine::instance().cg_sample(cg_id);
}

// Query coverage percentage
double sva_cg_coverage(int cg_id) {
    auto* cg = Engine::instance().get_covergroup(cg_id);
    return cg ? cg->coverage_pct() : 0.0;
}

// ==================================================================
//  Report
// ==================================================================
void sva_report(void) {
    Engine::instance().report("sva_report.txt");
}

}  // extern "C"
